name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add Conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Cache Conda packages
      uses: actions/cache@v3
      with:
        path: $CONDA/pkgs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    
    - name: Install dependencies
      run: |
        conda env create --file environment.yml --name myenv
        echo "conda activate myenv" >> $BASH_ENV

    - name: Lint with flake8
      run: |
        conda activate myenv
        conda install -y flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        conda activate myenv
        conda install -y pytest
        pytest
