name: Python Package using Conda

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add Conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Cache Conda packages
      uses: actions/cache@v3
      with:
        path: $CONDA/pkgs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda-
    
    - name: Install dependencies
      run: |
        conda env create --file environment.yml --name myenv
        echo "conda activate myenv" >> $BASH_ENV
    
    - name: Lint with flake8
      run: conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add Conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Cache Conda environment
      uses: actions/cache@v3
      with:
        path: $CONDA/envs/myenv
        key: ${{ runner.os }}-conda-env-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda-env-
    
    - name: Install dependencies
      run: |
        conda env create --file environment.yml --name myenv
        echo "conda activate myenv" >> $BASH_ENV
    
    - name: Test with pytest
      run: conda run -n myenv pytest
